CREATE DATABASE adventureworks1
WITH OWNER = postgres
     ENCODING = 'UTF8'
     LC_COLLATE = 'English_India.1252'
     LC_CTYPE   = 'English_India.1252'
     LOCALE_PROVIDER = 'libc'
     TABLESPACE = pg_default
     CONNECTION LIMIT = -1
     IS_TEMPLATE = False;
CREATE ROLE etl1 WITH LOGIN PASSWORD 'demopass';

GRANT ALL PRIVILEGES ON DATABASE adventureworks TO etl1;

GRANT USAGE, CREATE ON SCHEMA public TO etl1;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO etl1;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO etl1;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO etl;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO etl;



